services:
  postgres:
    image: 'postgres:latest'
    container_name: goalify
    environment:
      - 'POSTGRES_DB=goalify'
      - 'POSTGRES_PASSWORD=goalify'
      - 'POSTGRES_USER=goalify'
    ports:
      - '5432'
