CREATE TABLE  goal
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    effort      INTEGER                                 NOT NULL,
    status      INTEGER                                 NOT NULL,
    CONSTRAINT pk_goal PRIMARY KEY (id)
);