CREATE TABLE goalifyuser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_goalifyuser PRIMARY KEY (id)
);

ALTER TABLE goal
    ADD user_id BIGINT;

ALTER TABLE goalifyuser
    ADD CONSTRAINT uc_goalifyuser_email UNIQUE (email);

ALTER TABLE goal
    ADD CONSTRAINT FK_GOAL_ON_USER FOREIGN KEY (user_id) REFERENCES goalifyuser (id);