CREATE TABLE goal
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    effort      INTEGER                                 NOT NULL,
    status      INTEGER                                 NOT NULL,
    user_id     BIGINT,
    CONSTRAINT pk_goal PRIMARY KEY (id)
);

CREATE TABLE goalifyuser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_goalifyuser PRIMARY KEY (id)
);

ALTER TABLE goalifyuser
    ADD CONSTRAINT uc_goalifyuser_email UNIQUE (email);

ALTER TABLE goal
    ADD CONSTRAINT FK_GOAL_ON_USER FOREIGN KEY (user_id) REFERENCES goalifyuser (id);